### ISSUE TITLE
ReadLine and multiple error.

### ISSUE THREAD

**Issue by vishwaratna** [Leonmugen/ORtester#7]
**Trace**:

Traceback (most recent call last):
  File "C:\Users\DODO\Downloads\ORtester-master\ORtester-master\ortester.py", line 119, in <module>
    main()
  File "C:\Users\DODO\Downloads\ORtester-master\ORtester-master\ortester.py", line 52, in main
    payloadlist = open("payloads.list", "r").readlines()
  File "C:\Users\DODO\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 3122: character maps to <undefined>

**Comment by aldo-moreno-leon** [comment]
I added encoding="latin-1" on line 52, I tried with utf8 but that encoding is by default in python3.

**Comment by aldo-moreno-leon** [comment]
I recommend using Linux since this tool is intended to be used on that OS.
